client_config_backend: settings
client_config:
  client_id: 676307519429-9tai7eck5gdts2o33l5k6djabh25rh2a.apps.googleusercontent.com
  client_secret: YOtCX469MG_PlACYWBJbjTJi
save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json
get_refresh_token: True
oauth_scope:
  - https://www.googleapis.com/auth/drive.file